---
name: setup
description: set up the stage for building and testing
inputs:
  go-version:
    description: "The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks."
    required: false
    default: "1.22.x"
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
        check-latest: true
    - uses: ko-build/setup-ko@v0.7
    - name: install-goml
      shell: bash
      run: |
        TAG_NAME="$(curl -s https://api.github.com/repos/herrjulz/goml/releases/latest | jq -r '.tag_name')"
        curl -o /usr/local/bin/goml -L -s "https://github.com/herrjulz/goml/releases/download/${TAG_NAME}/goml-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m | sed -e 's/x86_64/amd64/')"
        chmod +x /usr/local/bin/goml
        goml -v
