name: Security
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Run at 00:00 on Sunday UTC time

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run gosec
        uses: securego/gosec@master
