name: Verify

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: Run verify-generate
      run: |
        make verify-generate

  golangci-lint:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: --timeout=10m
